// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uugjjxwmgwrqevfffouc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Z2pqeHdtZ3dycWV2ZmZmb3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNTAyMjQsImV4cCI6MjA4NDkyNjIyNH0.5ismu1l2-CIqMjGpHfVBInbRcD8RXJZupSWCOv0lfI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});